// Code generated by protoc-gen-go. DO NOT EDIT.
// source: producer/producer.proto

package producer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	structpb "google.golang.org/protobuf/types/known/structpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Timber struct {
	Context              *TimberContext   `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Timestamp            string           `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Content              *structpb.Struct `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Timber) Reset()         { *m = Timber{} }
func (m *Timber) String() string { return proto.CompactTextString(m) }
func (*Timber) ProtoMessage()    {}
func (*Timber) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc98445ab60afb7, []int{0}
}

func (m *Timber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timber.Unmarshal(m, b)
}
func (m *Timber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timber.Marshal(b, m, deterministic)
}
func (m *Timber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timber.Merge(m, src)
}
func (m *Timber) XXX_Size() int {
	return xxx_messageInfo_Timber.Size(m)
}
func (m *Timber) XXX_DiscardUnknown() {
	xxx_messageInfo_Timber.DiscardUnknown(m)
}

var xxx_messageInfo_Timber proto.InternalMessageInfo

func (m *Timber) GetContext() *TimberContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Timber) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Timber) GetContent() *structpb.Struct {
	if m != nil {
		return m.Content
	}
	return nil
}

type TimberCollection struct {
	Context              *TimberContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Items                []*Timber      `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TimberCollection) Reset()         { *m = TimberCollection{} }
func (m *TimberCollection) String() string { return proto.CompactTextString(m) }
func (*TimberCollection) ProtoMessage()    {}
func (*TimberCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc98445ab60afb7, []int{1}
}

func (m *TimberCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimberCollection.Unmarshal(m, b)
}
func (m *TimberCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimberCollection.Marshal(b, m, deterministic)
}
func (m *TimberCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimberCollection.Merge(m, src)
}
func (m *TimberCollection) XXX_Size() int {
	return xxx_messageInfo_TimberCollection.Size(m)
}
func (m *TimberCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_TimberCollection.DiscardUnknown(m)
}

var xxx_messageInfo_TimberCollection proto.InternalMessageInfo

func (m *TimberCollection) GetContext() *TimberContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *TimberCollection) GetItems() []*Timber {
	if m != nil {
		return m.Items
	}
	return nil
}

type TimberContext struct {
	KafkaTopic             string   `protobuf:"bytes,1,opt,name=kafka_topic,json=kafkaTopic,proto3" json:"kafka_topic,omitempty"`
	KafkaPartition         int32    `protobuf:"varint,2,opt,name=kafka_partition,json=kafkaPartition,proto3" json:"kafka_partition,omitempty"`
	KafkaReplicationFactor int32    `protobuf:"varint,3,opt,name=kafka_replication_factor,json=kafkaReplicationFactor,proto3" json:"kafka_replication_factor,omitempty"`
	EsIndexPrefix          string   `protobuf:"bytes,4,opt,name=es_index_prefix,json=esIndexPrefix,proto3" json:"es_index_prefix,omitempty"`
	EsDocumentType         string   `protobuf:"bytes,5,opt,name=es_document_type,json=esDocumentType,proto3" json:"es_document_type,omitempty"`
	AppMaxTps              int32    `protobuf:"varint,6,opt,name=app_max_tps,json=appMaxTps,proto3" json:"app_max_tps,omitempty"`
	AppSecret              string   `protobuf:"bytes,7,opt,name=app_secret,json=appSecret,proto3" json:"app_secret,omitempty"`
	DisableAppTps          bool     `protobuf:"varint,8,opt,name=disable_app_tps,json=disableAppTps,proto3" json:"disable_app_tps,omitempty"`
	AppGroupMaxTps         int32    `protobuf:"varint,9,opt,name=app_group_max_tps,json=appGroupMaxTps,proto3" json:"app_group_max_tps,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *TimberContext) Reset()         { *m = TimberContext{} }
func (m *TimberContext) String() string { return proto.CompactTextString(m) }
func (*TimberContext) ProtoMessage()    {}
func (*TimberContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc98445ab60afb7, []int{2}
}

func (m *TimberContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimberContext.Unmarshal(m, b)
}
func (m *TimberContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimberContext.Marshal(b, m, deterministic)
}
func (m *TimberContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimberContext.Merge(m, src)
}
func (m *TimberContext) XXX_Size() int {
	return xxx_messageInfo_TimberContext.Size(m)
}
func (m *TimberContext) XXX_DiscardUnknown() {
	xxx_messageInfo_TimberContext.DiscardUnknown(m)
}

var xxx_messageInfo_TimberContext proto.InternalMessageInfo

func (m *TimberContext) GetKafkaTopic() string {
	if m != nil {
		return m.KafkaTopic
	}
	return ""
}

func (m *TimberContext) GetKafkaPartition() int32 {
	if m != nil {
		return m.KafkaPartition
	}
	return 0
}

func (m *TimberContext) GetKafkaReplicationFactor() int32 {
	if m != nil {
		return m.KafkaReplicationFactor
	}
	return 0
}

func (m *TimberContext) GetEsIndexPrefix() string {
	if m != nil {
		return m.EsIndexPrefix
	}
	return ""
}

func (m *TimberContext) GetEsDocumentType() string {
	if m != nil {
		return m.EsDocumentType
	}
	return ""
}

func (m *TimberContext) GetAppMaxTps() int32 {
	if m != nil {
		return m.AppMaxTps
	}
	return 0
}

func (m *TimberContext) GetAppSecret() string {
	if m != nil {
		return m.AppSecret
	}
	return ""
}

func (m *TimberContext) GetDisableAppTps() bool {
	if m != nil {
		return m.DisableAppTps
	}
	return false
}

func (m *TimberContext) GetAppGroupMaxTps() int32 {
	if m != nil {
		return m.AppGroupMaxTps
	}
	return 0
}

type ProduceResult struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProduceResult) Reset()         { *m = ProduceResult{} }
func (m *ProduceResult) String() string { return proto.CompactTextString(m) }
func (*ProduceResult) ProtoMessage()    {}
func (*ProduceResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5dc98445ab60afb7, []int{3}
}

func (m *ProduceResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceResult.Unmarshal(m, b)
}
func (m *ProduceResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceResult.Marshal(b, m, deterministic)
}
func (m *ProduceResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceResult.Merge(m, src)
}
func (m *ProduceResult) XXX_Size() int {
	return xxx_messageInfo_ProduceResult.Size(m)
}
func (m *ProduceResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceResult.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceResult proto.InternalMessageInfo

func (m *ProduceResult) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func init() {
	proto.RegisterType((*Timber)(nil), "producer.Timber")
	proto.RegisterType((*TimberCollection)(nil), "producer.TimberCollection")
	proto.RegisterType((*TimberContext)(nil), "producer.TimberContext")
	proto.RegisterType((*ProduceResult)(nil), "producer.ProduceResult")
}

func init() { proto.RegisterFile("producer/producer.proto", fileDescriptor_5dc98445ab60afb7) }

var fileDescriptor_5dc98445ab60afb7 = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0x3a, 0xfa, 0xe5, 0xd2, 0xae, 0x78, 0x88, 0x85, 0x6a, 0x40, 0x15, 0x89, 0x51, 0x26,
	0xd1, 0x88, 0x4e, 0x48, 0x68, 0x3c, 0x51, 0x10, 0x68, 0x12, 0x48, 0x55, 0xd6, 0x27, 0x1e, 0x88,
	0x9c, 0xd4, 0xed, 0xac, 0x25, 0xb1, 0x65, 0xdf, 0x48, 0xdd, 0x2b, 0xcf, 0xbc, 0xf1, 0x5b, 0xf8,
	0x25, 0xfc, 0x05, 0xfe, 0x03, 0xaf, 0xc8, 0x76, 0xdc, 0x6e, 0x4c, 0xbc, 0xec, 0xed, 0xfa, 0x9c,
	0x93, 0x73, 0x4f, 0x7c, 0xaf, 0xd1, 0xbe, 0x90, 0x7c, 0x51, 0xa6, 0x54, 0x86, 0xae, 0x18, 0x0b,
	0xc9, 0x81, 0xe3, 0x96, 0x3b, 0x0f, 0x0e, 0x56, 0x9c, 0xaf, 0x32, 0x1a, 0x12, 0xc1, 0x42, 0x52,
	0x14, 0x1c, 0x08, 0x30, 0x5e, 0x28, 0xab, 0xdb, 0xb0, 0xe6, 0x94, 0x94, 0xcb, 0x50, 0x81, 0x2c,
	0x53, 0xb0, 0x6c, 0xf0, 0xdd, 0x43, 0x8d, 0x39, 0xcb, 0x13, 0x2a, 0xf1, 0x4b, 0xd4, 0x4c, 0x79,
	0x01, 0x74, 0x0d, 0xbe, 0x37, 0xf4, 0x46, 0x9d, 0xc9, 0xfe, 0x78, 0xd3, 0xd2, 0x4a, 0xde, 0x59,
	0x3a, 0x72, 0x3a, 0x7c, 0x80, 0xda, 0xc0, 0x72, 0xaa, 0x80, 0xe4, 0xc2, 0xaf, 0x0d, 0xbd, 0x51,
	0x3b, 0xda, 0x02, 0x1b, 0xc3, 0x02, 0xfc, 0x9d, 0xca, 0xd0, 0x66, 0x19, 0xbb, 0x2c, 0xe3, 0x33,
	0x93, 0x25, 0x72, 0xba, 0x20, 0x47, 0x7d, 0xd7, 0x2a, 0xcb, 0x68, 0xaa, 0xff, 0xe3, 0x36, 0xb9,
	0x0e, 0x51, 0x9d, 0x01, 0xcd, 0x95, 0x5f, 0x1b, 0xee, 0x8c, 0x3a, 0x93, 0xfe, 0xbf, 0x1f, 0x44,
	0x96, 0x0e, 0xfe, 0xd4, 0x50, 0xf7, 0x9a, 0x05, 0x7e, 0x82, 0x3a, 0x17, 0x64, 0x79, 0x41, 0x62,
	0xe0, 0x82, 0xa5, 0xa6, 0x61, 0x3b, 0x42, 0x06, 0x9a, 0x6b, 0x04, 0x3f, 0x43, 0xbb, 0x56, 0x20,
	0x88, 0x04, 0xa6, 0x03, 0x9a, 0x1f, 0xaf, 0x47, 0x3d, 0x03, 0xcf, 0x1c, 0x8a, 0x5f, 0x23, 0xdf,
	0x0a, 0x25, 0x15, 0x19, 0x4b, 0xcd, 0x4c, 0xe2, 0x25, 0x49, 0x81, 0x4b, 0x73, 0x1d, 0xf5, 0xe8,
	0x81, 0xe1, 0xa3, 0x2d, 0xfd, 0xc1, 0xb0, 0xf8, 0x10, 0xed, 0x52, 0x15, 0xb3, 0x62, 0x41, 0xd7,
	0xb1, 0x90, 0x74, 0xc9, 0xd6, 0xfe, 0x1d, 0x93, 0xa3, 0x4b, 0xd5, 0xa9, 0x46, 0x67, 0x06, 0xc4,
	0x23, 0xd4, 0xa7, 0x2a, 0x5e, 0xf0, 0xb4, 0xcc, 0x69, 0x01, 0x31, 0x5c, 0x0a, 0xea, 0xd7, 0x8d,
	0xb0, 0x47, 0xd5, 0xfb, 0x0a, 0x9e, 0x5f, 0x0a, 0x8a, 0x1f, 0xa3, 0x0e, 0x11, 0x22, 0xce, 0xc9,
	0x3a, 0x06, 0xa1, 0xfc, 0x86, 0x69, 0xdf, 0x26, 0x42, 0x7c, 0x26, 0xeb, 0xb9, 0x50, 0xf8, 0x11,
	0x42, 0x9a, 0x57, 0x34, 0x95, 0x14, 0xfc, 0xa6, 0x1d, 0x24, 0x11, 0xe2, 0xcc, 0x00, 0x3a, 0xd0,
	0x82, 0x29, 0x92, 0x64, 0x34, 0xd6, 0x32, 0x6d, 0xd1, 0x1a, 0x7a, 0xa3, 0x56, 0xd4, 0xad, 0xe0,
	0xb7, 0x42, 0x68, 0x9b, 0xe7, 0xe8, 0x9e, 0xe6, 0x57, 0x92, 0x97, 0xdb, 0x66, 0x6d, 0x7b, 0x3b,
	0x44, 0x88, 0x8f, 0x1a, 0xb7, 0x1d, 0x83, 0xa7, 0xa8, 0x3b, 0xb3, 0x33, 0x89, 0xa8, 0x2a, 0x33,
	0xc0, 0xf7, 0x51, 0xfd, 0xea, 0x95, 0xdb, 0xc3, 0xe4, 0xa7, 0x87, 0x5a, 0x95, 0x4e, 0xe2, 0x53,
	0xd4, 0xac, 0x6a, 0x7c, 0x63, 0xa2, 0x83, 0x2b, 0x4b, 0x71, 0xcd, 0x38, 0xd8, 0xfb, 0xf6, 0xeb,
	0xf7, 0x8f, 0x5a, 0x37, 0x68, 0xb9, 0x07, 0x74, 0xe2, 0x1d, 0xe1, 0xaf, 0xe8, 0x6e, 0xa5, 0x9a,
	0x12, 0x48, 0xcf, 0xf1, 0xe0, 0xe6, 0x4a, 0xb9, 0xfd, 0xfb, 0xbf, 0xf3, 0x43, 0xe3, 0xbc, 0x17,
	0xf4, 0x9c, 0x73, 0x9c, 0x68, 0xb3, 0x13, 0xef, 0x68, 0xfa, 0xea, 0xcb, 0xf1, 0x8a, 0xc1, 0x79,
	0x99, 0x8c, 0x53, 0x9e, 0x87, 0x53, 0x22, 0x19, 0xf0, 0x4f, 0x7c, 0x15, 0x26, 0xa6, 0x7a, 0x61,
	0xf6, 0x7f, 0xf3, 0xa0, 0xdf, 0xb8, 0x22, 0x69, 0x18, 0xe2, 0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x8d, 0x29, 0xab, 0xb7, 0xf5, 0x03, 0x00, 0x00,
}
