// Code generated by protoc-gen-go. DO NOT EDIT.
// source: loki.proto

package loki

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushRequest struct {
	Streams              []*Stream `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3b449635ad5185e, []int{0}
}

func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (m *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(m, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetStreams() []*Stream {
	if m != nil {
		return m.Streams
	}
	return nil
}

type Stream struct {
	Labels               string   `protobuf:"bytes,1,opt,name=labels,proto3" json:"labels,omitempty"`
	Entries              []*Entry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3b449635ad5185e, []int{1}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetLabels() string {
	if m != nil {
		return m.Labels
	}
	return ""
}

func (m *Stream) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type Entry struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Line                 string               `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3b449635ad5185e, []int{2}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Entry) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func init() {
	proto.RegisterType((*PushRequest)(nil), "loki.PushRequest")
	proto.RegisterType((*Stream)(nil), "loki.Stream")
	proto.RegisterType((*Entry)(nil), "loki.Entry")
}

func init() { proto.RegisterFile("loki.proto", fileDescriptor_a3b449635ad5185e) }

var fileDescriptor_a3b449635ad5185e = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0xc1, 0x4e, 0x84, 0x30,
	0x10, 0x86, 0x03, 0x22, 0x84, 0xa9, 0xa7, 0x1e, 0x0c, 0xe1, 0xa2, 0x21, 0xd1, 0x70, 0x2a, 0x09,
	0xc6, 0xc4, 0x17, 0x30, 0x5e, 0x4d, 0xd5, 0x07, 0x80, 0x64, 0xc4, 0xc6, 0x42, 0xd9, 0xb6, 0x1c,
	0xf6, 0xed, 0x37, 0x4c, 0xb7, 0xbb, 0xb7, 0xe9, 0x37, 0xff, 0x7c, 0xfd, 0x01, 0xb4, 0xf9, 0x57,
	0x62, 0xb5, 0xc6, 0x1b, 0x9e, 0xed, 0x73, 0xfd, 0x30, 0x19, 0x33, 0x69, 0xec, 0x88, 0x8d, 0xdb,
	0x6f, 0xe7, 0xd5, 0x8c, 0xce, 0x0f, 0xf3, 0x1a, 0x62, 0xcd, 0x2b, 0xb0, 0xcf, 0xcd, 0xfd, 0x49,
	0x3c, 0x6c, 0xe8, 0x3c, 0x7f, 0x86, 0xc2, 0x79, 0x8b, 0xc3, 0xec, 0xaa, 0xe4, 0xf1, 0xa6, 0x65,
	0xfd, 0x9d, 0x20, 0xe7, 0x17, 0x41, 0x19, 0x97, 0xcd, 0x07, 0xe4, 0x01, 0xf1, 0x7b, 0xc8, 0xf5,
	0x30, 0xa2, 0xde, 0x0f, 0x92, 0xb6, 0x94, 0xe7, 0x17, 0x7f, 0x82, 0x02, 0x17, 0x6f, 0x15, 0xba,
	0x2a, 0x25, 0x13, 0x0b, 0xa6, 0xf7, 0xc5, 0xdb, 0xa3, 0x8c, 0xbb, 0xe6, 0x07, 0x6e, 0x89, 0xf0,
	0x37, 0x28, 0x2f, 0xdd, 0x48, 0xc5, 0xfa, 0x5a, 0x84, 0xf6, 0x22, 0xb6, 0x17, 0xdf, 0x31, 0x21,
	0xaf, 0x61, 0xce, 0x21, 0xd3, 0x6a, 0xc1, 0x2a, 0xa5, 0xff, 0x69, 0x1e, 0x73, 0x3a, 0x79, 0x39,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x40, 0x6f, 0x67, 0x12, 0x01, 0x00, 0x00,
}
